name: Keep Render Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # roda a cada 15 min
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping no Render
        run: |
          HORA=$(date -u +%H)

          # Converte UTC para Brasil (UTC-3)
          HORA_BR=$(( (10#$HORA - 3 + 24) % 24 ))

          if [ $HORA_BR -ge 7 ] && [ $HORA_BR -lt 23 ]; then
            curl -s https://planta-cliniprev2-1.onrender.com/api/health
          else
            echo "Fora do horário"
          fi